#!/usr/bin/env python3
"""Print a Slurm batch script for one Stage 1 gate.

The generator only prints; it never writes a file and never calls sbatch.
Redirect stdout to a file, inspect it, then submit it yourself. The generated
script runs the preflight first (so the gate chain has its evidence) and then
exactly one training gate. Gates are never chained.

Example:
  python3 stage-1/scripts/make_slurm_script.py \
    --config stage-1/configs/qwen3.5-4b-full.yaml \
    --export /shared/$USER/tikz-production/export \
    --prepared /shared/$USER/tikz-stage1/prepared \
    --run-dir /shared/$USER/tikz-stage1/runs/qwen3.5-4b \
    --gate smoke-1000 \
    --python /shared/$USER/envs/qwen3.5-4b/bin/python \
    --wall-time 12:00:00 \
    > tikz-stage1-qwen-smoke.sbatch
"""
import argparse
import shlex
import sys
from pathlib import Path

import _bootstrap  # noqa: F401

from stage1 import cli, config as config_module
from stage1.util import parse_wall_time, require_absolute

TRAINING_GATES = ("overfit-100", "smoke-1000", "full")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Print (never submit) an sbatch script for one training gate.")
    parser.add_argument("--config", required=True, help="model config YAML")
    parser.add_argument("--export", required=True,
                        help="absolute cleaning export directory")
    parser.add_argument("--prepared", required=True,
                        help="absolute prepared directory")
    parser.add_argument("--run-dir", required=True, help="absolute run directory")
    parser.add_argument("--gate", required=True, choices=TRAINING_GATES)
    parser.add_argument("--python", required=True,
                        help="absolute path to the pinned environment python")
    parser.add_argument("--wall-time", default="12:00:00",
                        help="Slurm wall time (minutes, MM:SS, HH:MM:SS or D-HH:MM:SS)")
    parser.add_argument("--partition", default="rtxpro6k")
    parser.add_argument("--gres", default="gpu:rtxpro6k:1")
    parser.add_argument("--cpus", type=int, default=32)
    parser.add_argument("--job-name", default=None)
    parser.add_argument("--output", default=None,
                        help="Slurm --output pattern (default slurm-stage1-%%j.out)")
    parser.add_argument("--local-files-only", action="store_true",
                        help="export HF_HUB_OFFLINE=1 and TRANSFORMERS_OFFLINE=1")
    parser.add_argument("--no-preflight-first", action="store_true",
                        help="omit the preflight step (only when it already passed)")
    return parser


def build_script(args, config) -> str:
    scripts_dir = Path(__file__).resolve().parent
    python_path = require_absolute(args.python, "--python")
    export_dir = require_absolute(args.export, "--export")
    prepared_dir = require_absolute(args.prepared, "--prepared")
    run_dir = require_absolute(args.run_dir, "--run-dir")
    config_path = Path(args.config).resolve()
    if not config_path.is_file():
        raise config_module.ConfigError(f"Config file not found: {config_path}")
    if args.cpus < 1:
        raise config_module.ConfigError("--cpus must be positive")
    minutes = parse_wall_time(args.wall_time)
    job_name = args.job_name or f"tikz-stage1-{config.model.adapter}-{args.gate}"
    output = args.output or "slurm-stage1-%j.out"

    def quote(value):
        return shlex.quote(str(value))

    lines = [
        "#!/bin/bash -l",
        f"#SBATCH --job-name={job_name}",
        f"#SBATCH --partition={args.partition}",
        f"#SBATCH --gres={args.gres}",
        "#SBATCH --nodes=1",
        "#SBATCH --ntasks=1",
        f"#SBATCH --cpus-per-task={args.cpus}",
        f"#SBATCH --time={args.wall_time}",
        "#SBATCH --export=NONE",
        f"#SBATCH --output={output}",
        "#",
        "# Generated by stage-1/scripts/make_slurm_script.py.",
        "# This generator never submits anything: inspect this file, then run",
        "#   sbatch <this-file>",
        "# yourself. Stage 1 runs exactly one gate per job; gates never chain",
        "# automatically.",
        f"# Requested wall time: {minutes} minutes.",
        "set -euo pipefail",
        "unset SLURM_EXPORT_ENV",
        f"PYTHON={quote(python_path)}",
        f"SCRIPTS={quote(scripts_dir)}",
        f"CONFIG={quote(config_path)}",
        f"EXPORT={quote(export_dir)}",
        f"PREPARED={quote(prepared_dir)}",
        f"RUN_DIR={quote(run_dir)}",
        'echo "== environment =="',
        '"$PYTHON" --version',
        "command -v nvidia-smi >/dev/null && nvidia-smi --query-gpu=name,memory.total --format=csv || true",
    ]
    if args.local_files_only:
        lines += [
            "export HF_HUB_OFFLINE=1",
            "export TRANSFORMERS_OFFLINE=1",
        ]
    lines += [
        'echo "== stage 1 preflight =="',
    ]
    preflight_cmd = (
        '"$PYTHON" "$SCRIPTS/preflight.py" --config "$CONFIG" '
        '--export "$EXPORT" --prepared "$PREPARED" --run-dir "$RUN_DIR"')
    if args.local_files_only:
        preflight_cmd += " --local-files-only"
    if args.no_preflight_first:
        lines += [
            "# Preflight step omitted by request; the gate will refuse to start",
            "# unless passing preflight evidence already exists for this identity.",
            f"# {preflight_cmd}",
        ]
    else:
        lines.append(preflight_cmd)
    train_cmd = (
        f'"$PYTHON" "$SCRIPTS/train.py" --config "$CONFIG" '
        f'--export "$EXPORT" --prepared "$PREPARED" --run-dir "$RUN_DIR" '
        f'--gate {quote(args.gate)}')
    if args.local_files_only:
        train_cmd += " --local-files-only"
    lines += [
        'echo "== stage 1 training gate: ' + args.gate + ' =="',
        train_cmd,
        'echo "== stage 1 gate finished =="',
        'echo "Metrics and gate evidence are under $RUN_DIR"',
        "",
    ]
    return "\n".join(lines)


def main(argv) -> int:
    args = build_parser().parse_args(argv)
    config = config_module.load_config(args.config)
    script = build_script(args, config)
    sys.stdout.write(script)
    return 0


if __name__ == "__main__":
    sys.exit(cli.run(main))
